MyBlog/DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('blog.urls', 'blog'),namespace='blog')),

]

MyBlog/MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('blog.urls', 'blog'),namespace='blog')),
    url(r'', include(('comments.urls', 'comments'), namespace='comments')),
    url(r'', include(('account.urls', 'account'), namespace='account')),

]

MyBlog/blog/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category_name>\w+)$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^author/(?P<author_name>\w+)$', views.AuthorDetailView.as_view(), name='author_detail'),
    url(r'^tags/(?P<tag_name>\w+)$', views.TagDetailView.as_view(), name='tag_detail'),
    url(r'(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<article_id>\d+)-(?P<slug>\S+).html$',views.ArticleDetailView.as_view(),name='detail'),
]

MyBlog/comments/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^article/(?P<article_id>\d+)/postcomment$', views.CommentPostView.as_view(), name='postcomment'),
]

MyBlog/comments/models.py
from django.db import models
from django.conf import settings

from  blog.models import Article


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', verbose_name="上级评论", blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['created_time']

    class Meta:
        ordering = ['created_time']
        verbose_name = "评论"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.body

MyBlog/comments/forms.py
#!/usr/bin/env python
# encoding: utf-8
from .models import Comment
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class CommentForm(ModelForm):
    url = forms.URLField(label='网址', required=False)
    email = forms.EmailField(label='电子邮箱', required=False)
    name = forms.CharField(label='姓名')
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comment
        fields = ['body']

MyBlog/comments/views.py
from django.shortcuts import render

# Create your views here.
from .models import Comment
from blog.models import Article
from .forms import CommentForm
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import get_user_model


class CommentPostView(FormView):
    form_class = CommentForm
    template_name = 'blog/articledetail.html'

    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['article_id']
        url = reverse('blog:detail', kwargs={'article_id': article_id})
        return HttpResponseRedirect(url)

    def form_invalid(self, form):
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)

        return self.render_to_response({
            'form': form,
            'article': article
        })

    def form_valid(self, form):
        """提交的数据验证合法后的逻辑"""
        user = self.request.user

        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)
        if not self.request.user.is_authenticated:
            email = form.cleaned_data['email']
            username = form.cleaned_data['name']

            user = get_user_model().objects.create_user(username=username, email=email, password=None)
        author_id = user.pk

        comment = form.save(False)
        comment.article = article

        comment.author = get_user_model().objects.get(pk=author_id)

        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comment.objects.get(pk=form.cleaned_data['parent_comment_id'])
            comment.parent_comment = parent_comment

        comment.save(True)

        return HttpResponseRedirect(article.get_absolute_url())

MyBlog/templates/comments/tags/comment_item.html
{% load blog_tags %}
<li class="comment even thread-even depth-{{ depth }} parent" id="comment-{{ comment_item.pk }}">
    <div id="div-comment-{{ comment_item.pk }}" class="comment-body">
        <div class="comment-author vcard">
            <img alt=""
                 src="{{ comment_item.author.email|gravatar_url:150 }}"
                 srcset="{{ comment_item.author.email|gravatar_url:150 }}"
                 class="avatar avatar-96 photo" height="96" width="96"> <cite class="fn"><a
                href="#" rel="external nofollow"
                class="url">{{ comment_item.author.username }}</a></cite><span
                class="says">说道：</span></div>

        <div class="comment-meta commentmetadata"><a
                href="#">
            {{ comment_item.created_time }}</a></div>

        <p>{{ comment_item.body }}</p>

        <div class="reply"><a rel="nofollow" class="comment-reply-link"
                              href="javascript:void(0)"
                              onclick="do_reply({{ comment_item.pk }})"
                              aria-label="回复给{{ comment_item.author.username }}">回复</a></div>
    </div>

</li><!-- #comment-## -->

MyBlog/templates/comments/tags/post_comment.html
<div id="comments" class="comments-area">

    <div id="respond" class="comment-respond">
        <h3 id="reply-title" class="comment-reply-title">发表评论
            <small><a rel="nofollow" id="cancel-comment-reply-link" href="/wordpress/?p=3786#respond"
                      style="display:none;">取消回复</a></small>
        </h3>
        <form action="{% url 'comments:postcomment' article.pk %}" method="post" id="commentform"
              class="comment-form">{% csrf_token %}
            {% comment %}<p class="comment-notes"><span id="email-notes">电子邮件地址不会被公开。</span> 必填项已用<span class="required">*</span>标注
            </p>{% endcomment %}
            <p class="comment-form-comment">
                {{ form.body.label_tag }}
                {{ form.body }}
                {{ form.body.errors }}
                {% comment %}<label for="comment">评论</label> <textarea id="comment" name="comment"
                                                                                      cols="45" rows="8"
                                                                                      maxlength="65525"
                                                                                      aria-required="true"
                                                                                      required="required"></textarea>{% endcomment %}
            </p>
            <p class="comment-form-author">
                {% if not form.name.is_hidden %}
                    {{ form.name.label_tag }}
                {% endif %}
                {{ form.name }}
                {{ form.name.errors }}
                {% comment %}<label for="author">姓名 <span class="required">*</span></label>
                <input id="author" name="author" type="text" value="" size="30" maxlength="245" aria-required='true'
                       required='required'/></p>{% endcomment %}

            <p class="comment-form-email">
                {% comment %}    <label for="email">电子邮件 <span class="required">*</span></label> <input
                    id="email" name="email" type="text" value="" size="30" maxlength="100"
                    aria-describedby="email-notes" aria-required='true' required='required'/>{% endcomment %}
                {% if not form.email.is_hidden %}
                    {{ form.email.label_tag }}
                {% endif %}
                {{ form.email }}
                {{ form.email.errors }}
            </p>
            {% comment %}<p class="comment-form-url">
                {{ form.url.label_tag }}
                {{ form.url }}
                {{ form.url.errors }}

            </p>{% endcomment %}
            {{ form.parent_comment_id }}

            <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="发表评论"/>
                <small class="cancel-comment" id="cancel_comment" style="display: none">
                    <a href="javascript:void(0)" id="cancel-comment-reply-link" onclick="cancel_reply()">取消回复</a>
                </small>
            </p>
        </form>
    </div><!-- #respond -->

</div><!-- #comments .comments-area -->